-- DROP TABLE EMPLOYEE
CREATE TABLE [dbo].[EMPLOYEE](
	[EMPLOYEE_ID] BIGINT NOT NULL IDENTITY(1,1), 
	[FIRST_NAME] [varchar](50) NOT NULL,
	[LAST_NAME] [varchar](50) NULL,
	[BORN] DATETIME NULL, 
	[BIRTH_PLACE] VARCHAR(50) NULL, 
	[GENDER] CHAR, 	
	[EMAIL] [varchar](50) NULL,
	[USERNAME] [varchar](25) NOT NULL,
	[BEGUN] DATETIME NULL, 
	[ENDED] DATETIME NULL, 	
	CONSTRAINT PK_EMPLOYEE	PRIMARY KEY ([EMPLOYEE_ID] ASC)
)
CREATE INDEX IX_EMPLOYEE_NAME ON EMPLOYEE(FIRST_NAME, LAST_NAME);
CREATE INDEX IX_EMPLOYEE_BIRTH ON EMPLOYEE(BORN);
CREATE INDEX IX_EMPLOYEE_USERNAME ON EMPLOYEE(USERNAME);

-- DROP TABLE ORGANIZATION 

CREATE TABLE ORGANIZATION 
(
	UNIT_ID INT NOT NULL IDENTITY(1,1), 
	UNIT_NAME VARCHAR(50) NOT NULL, 	
	PARENT_ID INT NULL
	, CONSTRAINT PK_ORGANIZATION PRIMARY KEY (UNIT_ID) 
	, CONSTRAINT FK_ORGANIZATION_UNIT_ID FOREIGN KEY (PARENT_ID) REFERENCES ORGANIZATION 
)
CREATE INDEX IX_ORGANIZATION ON ORGANIZATION(UNIT_NAME)

-- DROP TABLE POSITION

CREATE TABLE POSITION 
( POSITION_ID INT NOT NULL IDENTITY(1,1), 
POSITION_NAME VARCHAR(50) NOT NULL, 
CONSTRAINT PK_POSITION PRIMARY KEY (POSITION_ID)); 


-- DROP TABLE JOB
CREATE TABLE JOB
(
	JOB_ID INT NOT NULL IDENTITY(1,1), 
	JOB_NAME VARCHAR(50) NOT NULL, 
	EMPLOYEE_ID BIGINT NOT NULL, 
	POSITION_ID INT NOT NULL,
	UNIT_ID INT NOT NULL,  
	BEGUN  DATETIME NULL, 
	ENDED DATETIME NULL, 
	CONSTRAINT PK_JOB PRIMARY KEY (JOB_ID), 
	CONSTRAINT FK_JOB_EMPLOYEE foreign key (EMPLOYEE_ID) REFERENCES EMPLOYEE, 
	CONSTRAINT FK_JOB_POSITION foreign key (POSITION_ID) REFERENCES POSITION,
	CONSTRAINT FK_JOB_UNIT foreign key (UNIT_ID) REFERENCES ORGANIZATION 
)


-- DROP TABLE HIERARCHY 
create table HIERARCHY 
(	HIERARCHY_ID INT NOT NULL IDENTITY (1,1), 
	EMPLOYEE_ID BIGINT NOT NULL, 
    SUPER_ID BIGINT NOT NULL, 
    BEGUN DATETIME NULL,
    ENDED DATETIME NULL, 
    CONSTRAINT PK_HIERARCHY PRIMARY KEY (HIERARCHY_ID), 
    CONSTRAINT FK_HIERARCHY_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE, 
    CONSTRAINT FK_HIERARCHY_SUPER FOREIGN KEY (SUPER_ID) REFERENCES EMPLOYEE
    ); 
    
    
SET IDENTITY_INSERT POSITION ON; 

INSERT INTO dbo.POSITION (POSITION_ID, POSITION_NAME) VALUES (1,'CEO');
INSERT INTO dbo.POSITION (POSITION_ID, POSITION_NAME) VALUES (2,'DIRECTOR');
INSERT INTO dbo.POSITION (POSITION_ID, POSITION_NAME) VALUES (3,'GENERAL MANAGER');
INSERT INTO dbo.POSITION (POSITION_ID, POSITION_NAME) VALUES (4,'MANAGER');
INSERT INTO dbo.POSITION (POSITION_ID, POSITION_NAME) VALUES (5,'SUPERVISOR');
INSERT INTO dbo.POSITION (POSITION_ID, POSITION_NAME) VALUES (6,'STAFF');
INSERT INTO dbo.POSITION (POSITION_ID, POSITION_NAME) VALUES (7,'OPERATOR');
    