SET NOCOUNT ON;
DECLARE @X TABLE (UNIT_ID INT);
INSERT @X VALUES(1),(2),(3),(4),(5),(6),(7);
SELECT * FROM @X;
DECLARE @ALL VARCHAR(MAX)

SELECT @ALL = (
SELECT ';' + ISNULL(CONVERT(VARCHAR,UNIT_ID),'')
FROM @X FOR XML PATH('')); 

SELECT @ALL=SUBSTRING(@ALL, 2, LEN(@ALL)-1);

SELECT @ALL AS [ALL];