SELECT R.ROUTINE_CATALOG [oDB],  R.ROUTINE_TYPE [oType], r.ROUTINE_NAME [oName], R.ROUTINE_DEFINITION [oDef], r.CREATED, r.LAST_ALTERED
FROM INFORMATION_SCHEMA.Routines r 
ORDER BY R.ROUTINE_TYPE, R.ROUTINE_NAME
-- where r.SPECIFIC_NAME  <> r.routine_name